### PR TITLE
Revied some variable names, added docs, added demo to docs folder.

### PR DESCRIPTION
**Pull request by taylorpatti**
@david-pl I made the variable and docstring tweaks you suggested. Also, there is a now a band structure/decay rate plotting example tutorial in the /docs/src directory entitled "collective_modes_demo.jl" - I left it as a simple program because I'm not sure how you'd like somethin that involved documented.

One note on the docs - I think that I have left some step out of the documentation workflow because my docstrings don't show up when I run help on the new functions. In particular, running the makefile.jl results in errors about "collective_modes" not existing. This is my first Julia package so I'm sure it's just some step I'm unaware of - just let me know and I'll fix it.

I was thinking that next I'd do the infinite 2D case afterall instead of the finite 1D case. It's a lot more interesting and useful, I'd say.

### CODE REVIEW

**Comment by david-pl** [comment]
Cool, thanks!
The reason why your docstrings aren't showing up when you view the help are the extra linebreaks you put between the docstring and the function definition. For example this line here: https://github.com/qojulia/CollectiveSpins.jl/blob/7a810dcc55209555ce8b5bfd784c03f9543d8606/src/collective_modes.jl#L25 needs to go.
Sorry I must have missed that in your original PR.

**Comment by taylorpatti** [comment]
Oh man, what a detail - thanks!

I also wanted to know your guys' preference on something for the infinie 2D functions. The imaginary part has a nice, well-behaved, closed form, but the real part actually has a divergence that we can renormalize by introducing cut-off frequencies and limiting reciprocal lattice vectors. So basically, we can have a pretty decent, yet still approximate, answer without using too, too many resources, but it's never exact. Does this work for you guys or do you want a finite version instead?

**Comment by david-pl** [comment]
What you're asking sounds a bit similar to the way we handle the energy shifts due to dipole-dipole interaction. The shifts would diverge when the distance between atoms goes to 0, so we renormalize that to 0 in order to avoid that. In that sense, what you're suggesting sounds fine to me.

I guess you want to do the 2D case in a different PR, right? I'd merge this one then.

**Comment by taylorpatti** [comment]
Yeah, probably merging this one is a good idea in case I don't get to the 2D stuff for awhile. This PR also corrects a bug in the Gamma function for certain values, so it's always good to get that fixed.

**Pull request merged**
